###
POST http://localhost:8080/register
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTc0Mzk2ODQ1OX0.cJfYHv2VDOIkRHAfGrflXurBgzgHNQoDv39OnIhk2VI

{
    "name":"julio",
    "email":"julio@gmail.com",
    "password":"@Xlr81998"
}

###
POST http://localhost:8080/login
Content-Type: application/json

{
    "email":"marcos@gmail.com",
    "password":"@Xlr81998"
}